name: crud-in-one

services:
  database:
    type: mysql
    portforward: 33062
    creds:
      user: crud_user
      password: password
      database: crud_db

  vanilla:
    type: php:8.2
    via: nginx
    webroot: ./vanilla
    ssl: false
    scanner: false
    composer_version: false

  node:
    type: node:18
    scanner: false
    ssl: false
    ports: 
      - '3000:3000' # API
      - '5173:5173' # React
      - '5174:5174' # Vue
    globals:
      pnpm: latest
    command: cd ./api && pnpm nodemon . # Start API Server

proxy:
  vanilla_nginx: 
    - vanilla.crud.localhost

  node:
    - api.crud.localhost:3000
    - react.crud.localhost:5173
    - vue.crud.localhost:5174

tooling:
  node:
    service: node

  pnpm:
    service: node

  api:
    service: node
    cmd: cd ./api && pnpm nodemon .

  react:
    service: node
    cmd: cd ./react && pnpm run dev

  vue:
    service: node
    cmd: cd ./vue && pnpm run dev


