name: crud-in-one

services:
  database:
    type: mysql
    portforward: 33062
    creds:
      user: crud_user
      password: password
      database: crud_db

  vanilla:
    type: php:8.2
    via: nginx
    webroot: ./vanilla
    ssl: false
    scanner: false
    composer_version: false

  node:
    type: node:18
    scanner: false
    ssl: false
    ports: 
      - '3000:3000' # API
      - '5173:5173' # React
    build:
      - npm install -G pnpm

proxy:
  vanilla_nginx: 
    - vanilla.crud.localhost

  node:
    - react.crud.localhost:5173
    - api.crud.localhost:3000

tooling:
  node:
    service: node

  pnpm:
    service: node

  dev-react:
    service: node
    cmd: cd ./react && pnpm run dev

  dev-api:
    service: node
    cmd: cd ./api && pnpm nodemon .
